service: employee-analytics-service

provider:
  name: aws
  
  region: ap-south-1
  memorySize: 512
  timeout: 30

  iam:
    role: arn:aws:iam::979176640062:role/Lambda_execution_role
  ecr:
    images:
      latest:
        path: ../../ # Specify the root directory of the Docker context
        file: src/Dockerfile # Specify the relative path to the Dockerfile


functions:
  new_dev:
    name: new_dev
    timeout: 900
    image:
      name: latest

