service: employee-analytics-service

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  memorySize: 512
  timeout: 30
  architecture: x86_64

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"


functions:
  apiHandler:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: process
          method: post

package:
  exclude:
    - __pycache__/**
    - tests/**
    - README.md

plugins:
  - serverless-python-requirements

ecr:
  images:
    latest:
      path: ../../  # This points to the root directory of your project
      file: src/Dockerfile  # This points to the Dockerfile inside the 'src' directory

custom:
  pythonRequirements:
    dockerizePip: true

  ecr:
    images:
      latest:
        path: ../ # Specify the root directory of the Docker context
        file: src/Dockerfile # Specify the relative path to the Dockerfile
