
name: Deploy Staging
on:
  push:
    branches:
      - staging


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::979176640062:role/github-action-role
          aws-region: ap-south-1
          mask-aws-account-id: 'false'

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Serverless Framework
        run: npm install -g serverless@3.38.0

      - name: Install Serverless Compose
        run: npm install -g @serverless/compose

      - name: Deploy Lambda functions
        run: |
          sls deploy --stage staging
        working-directory: ./src
        
        env:
          AWS_REGION: ap-south-1
